name: ios_club_app
description: "西建大iOS Club出品的社团软件。"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.1.9+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.2
  http: ^1.3.0
  intl: ^0.20.2
  permission_handler: ^12.0.0+1
  shared_preferences_android: ^2.4.7
  crypto: ^3.0.6
  flutter_local_notifications: ^19.1.0
  url_launcher: ^6.3.1
  android_intent_plus: ^5.3.0
  package_info_plus: ^8.3.0
  home_widget: ^0.7.0+1
  path_provider: ^2.1.5
  open_file: ^3.5.10
  html: ^0.15.5
  flutter_staggered_grid_view: ^0.7.0
  dio: ^5.8.0+1
  timezone: ^0.10.0
  flutter_native_splash: ^2.4.6
  flutter_svg: ^2.1.0
  numberpicker: ^2.1.2
  fl_chart: ^1.0.0
  archive: ^4.0.7
  flutter_background_service: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/iconfont/iconfont.json

  fonts:
    - family: IconFont
      fonts:
        - asset: assets/iconfont/iconfont.ttf


flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon.png
  android: true
  ios: true
  color_dark: "#121212"
  image_dark: assets/icon.png
  web: false